### ISSUE TITLE
Strange behaviour with the Divi library

### ISSUE THREAD

**Issue by YesPapa** [garethjmsaunders/wp-customise-divi-project#1]
Hi,

It seems that the script blocks the access to the Divi library after the last releases.

Thank you.

**Comment by YesPapa** [comment]
You have to remove this lines to be compatible with the new Divi theme:

`$labels = array(
'name' => _x( 'Layouts', 'Layout type general name', 'Divi' ),
'singular_name' => _x( 'Layout', 'Layout type singular name', 'Divi' ),
'add_new' => _x( 'Add New', 'Layout item', 'Divi' ),
'add_new_item' => __( 'Add New Layout', 'Divi' ),
'edit_item' => __( 'Edit Layout', 'Divi' ),
'new_item' => __( 'New Layout', 'Divi' ),
'all_items' => __( 'All Layouts', 'Divi' ),
'view_item' => __( 'View Layout', 'Divi' ),
'search_items' => __( 'Search Layouts', 'Divi' ),
'not_found' => __( 'Nothing found', 'Divi' ),
'not_found_in_trash' => __( 'Nothing found in Trash', 'Divi' ),
'parent_item_colon' => '',
);

$args = array(
'labels' => $labels,
'public' => false,
'can_export' => true,
'query_var' => false,
'has_archive' => false,
'capability_type' => 'post',
'hierarchical' => false,
'supports' => array( 'title', 'editor', 'thumbnail', 'excerpt', 'comments', 'revisions', 'custom-fields' ),
);

register_post_type( 'et_pb_layout', apply_filters( 'et_pb_layout_args', $args ) );`

**Comment by garethjmsaunders** [comment]
Is it not working for you? I have it working fine on one of my client sites: http://www.pittenweemproperties.com/properties/

**Comment by YesPapa** [comment]
The slug/script works but that causes an issue to access the Divi library. They have a thread on the Divi forum about it.

**Comment by garethjmsaunders** [comment]
Do you mean the "Add from Library" option beneath each section?

Save to Library and Load from Library both work for me.

**Comment by YesPapa** [comment]
Nope. It is the "Divi Library" wordpress menu at the bottom of the sidebar menu.

**Comment by jdolan18** [comment]
Do we need to remove all of that code that you listed above or just a portion of it?

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WEB—Fix wp-divi-customise-project](https://trello.com/c/t1ZwbRko/656-web-fix-wp-divi-customise-project)

**Comment by garethjmsaunders** [comment]
I have rewritten this plugin from the ground up. It will be available shortly.

I've just tested this with the latest version of Divi v4.27.1 and my new plugin. It is working as expected.
