### ISSUE TITLE
Conflicts with Yoast

### ISSUE THREAD

**Issue by fatysnax** [garethjmsaunders/wp-customise-divi-project#2]
Using this code, Yoast controls no longer appear on the projects/[new name] pages.

**Comment by garethjmsaunders** [comment]
Thanks for the heads-up. I've been wanting to rewrite this for a while ... I'll take a look at this.

**Comment by garethjmsaunders** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [WEB—Fix wp-divi-customise-project](https://trello.com/c/t1ZwbRko/656-web-fix-wp-divi-customise-project)

**Comment by fatysnax** [comment]
That link is private.

**Comment by garethjmsaunders** [comment]
Yes, it's on my personal Trello current projects board ... I linked to this issue from there. I actually didn't realise it would post a link back here too ... every day's a school day.

**Comment by garethjmsaunders** [comment]
@fatysnax I've been doing some testing this evening on this issue. Does it work for you as expected if you first flush the permalinks, i.e. go to **Settings > Permalinks** and simply click on the **Save Changes button**?

**Comment by fatysnax** [comment]
I tried to save the permalinks a few times, but the Yoast controls never appear. 

Note: I had a portion of the code commented out per some troubleshooting comments I found earlier (the last two groups for labels and args), so I un-commented them out and tried again with no luck.

**Comment by garethjmsaunders** [comment]
@fatysnax Thanks for checking -- it's all working for me perfectly with just my plugin plus Yoast. Sometimes if I switch between project and the plugin, it gets stuck and flushing the permalinks works for me.

What other plugins do you have installed?

**Comment by fatysnax** [comment]
I've tested the plugins by deactivating them all but Yoast and that didn't do the trick, though I did not flush the permalinks when I did that.

Not a lot that would conflict, I don't think. It's pretty lean: Divi Mega Pro, Wordfence, Hummingbird, Smush, and Site Kit.

**Comment by garethjmsaunders** [comment]
@fatysnax I have been working on a replacement for this plugin. Try the following:

1. Go to [https://github.com/garethjmsaunders/wp-divi-rename-project-cpt](https://github.com/garethjmsaunders/wp-divi-rename-project-cpt)
2. Click on the green `<>Code` button and select `Download Zip`.
3. Deactivate my old WP Divi Customise Project plugin.
4. Install this plugin on your website and activate it.
5. Navigate to `Settings > Rename Divi Projects`.
6. Update your preferred settings in the options screen and save them.
7. Test your site with Yoast SEO and other plugins as required.

I've tested this using the plugins you listed and it's all working fine for me.

My plan is to make this plugin available commercially, but (assuming that it works as expected) I'd like you to have it for free. I will be making the new repository private in due course.

Let me know please how you get on.

Thanks

Gareth

**Comment by garethjmsaunders** [comment]
This code has now been deprecated in favour of my new plugin, Rename Divi Projects, on Divi Marketplace.

[https://www.elegantthemes.com/marketplace/rename-divi-projects/](https://www.elegantthemes.com/marketplace/rename-divi-projects/)
